development:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: tc_development
      logger: false
  options:
    raise_not_found_error: false

test:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: tc_test
      logger: false
  options:
    raise_not_found_error: false

production:
  sessions:
    default:
      hosts:
        - flame.mongohq.com:27048
      database: app5538187
      username: heroku
      password: heroku
      logger: false
  options:
    raise_not_found_error: false
