development:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: techcor_development
      logger: false
  options:
    raise_not_found_error: false

test:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: techcor_test
      logger: false
  options:
    raise_not_found_error: false

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      logger: false
  options:
    raise_not_found_error: false
